export {default as Navbar} from "./Navbar.jsx";
export {default as Hero} from "./Hero.jsx"
export {default as AboutHome} from "./AboutHome.jsx"
export {default as ServicesHome}from "./ServicesHome.jsx"
export {default as Footer}from "./Footer.jsx"
export {default as Blog}from "./Blog.jsx"
export {default as Loading}from "./Loading.jsx"
export {default as Testimonial} from "./Testimonial.jsx"
export {default as SocialMediaNav} from "./SocialMediaNav.jsx"
export {default as Namebar} from "./Namebar.jsx"
